version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
    ports:
      - 9042:9042
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
    depends_on:
      cassandra1:
        condition: service_healthy
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
    depends_on:
      cassandra2:
        condition: service_healthy
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60

  flask_server:
    image: my_flask_server
    mem_limit: 1g
    # container_name: flask_server
    depends_on:
      cassandra3:
        condition: service_healthy
    # ports:
    #   - 8089:8089
    ports:
      - "8089-8091:8089"
    deploy:
      replicas: 3
    networks:
      - cassandra-net

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask_server
    networks:
      - cassandra-net


networks:
  cassandra-net:
    driver: bridge
